### ISSUE TITLE
Password protected videos

### ISSUE THREAD

**Issue by lpupp** [KennethJudd/CompEcon2020#6]
the video lectures for Version control using Git, Automatic differentiation, and Homotopy are password protected. I'm not sure if I overlooked an email.

Where can I find the password?

Thanks in advance!

**Comment by pm036929** [comment]
Hi!
Currently, the videos are meant for the students attending the course. The videos will be released for public at a later stage. Please send me an email if I shall add you to the list of students (and send you the password): philipp.mueller@business.uzh.ch .
Best,
Philipp
